(add-load-path "." :relative)
(add-load-path "./compilers" :relative)

(use carrot-classes)
(use read)
(use check)
(use to-js)

(define (main args)
  (let ([heap (sexprs->carrot-expr (read-from-string (cadr args)))])
    (format #t "Correctly Typed: ~S\n" (check-program heap))
    (newline)
    (display ";;=> ")
    (flush)
    (sys-exec "node" (list "" "-p" (compile heap)))))
