(add-load-path "." :relative)
(add-load-path "./compilers" :relative)

(use carrot-classes)
(use read)
(use check)
(use to-js)

(define (main args)
  (let ([heap (sexprs->carrot-expr (read))])
    (print (ref heap 'main))
    (format #t "Correctly Typed: ~S\n" (check-program heap))
    (newline)
    (let1 code (compile heap)
          (print code)
          (display ";;=> ")
          (flush)
          (sys-exec "node" (list "" "-p" code)))))
